// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://imgccjokqoysspbqespe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImltZ2Njam9rcW95c3NwYnFlc3BlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5MTQ2MzksImV4cCI6MjA2MjQ5MDYzOX0.qMfsyLHLsR1Ee4gaJyQCnEL7B8DkvxoygMyKYlqmJJA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);